### ISSUE TITLE
CMM stucks when clicking on Member

### ISSUE THREAD

**Issue by johnnyontheweb** [idea-statica/ccm-examples#12]
Hello, I'm using the attached modelBIM with Code Check manager - the CCM application stucks every time I try to open Member 60 - see screenshot below.

![CCM_after2ndClickOnMember_stucking](https://user-images.githubusercontent.com/10365055/100071887-d962a180-2e3b-11eb-9947-5bfbd797c469.PNG)

I have IDEA StatiCa v.20.1.3471.1 on Windows 10 20H2.

I'm also having troubles in importing members from the calling application - CCM always show the error below when pressing "Member" button. The second time the member n. 60 is correctly acquired. Please note that prior to 20.1, CCM terminated. In every case, no log is available.

![CCM_1stClickOnMember](https://user-images.githubusercontent.com/10365055/100071989-f8613380-2e3b-11eb-852e-21db83872db0.PNG)

Can you help on both issues? thanks in advance

[test.zip](https://github.com/idea-statica/ccm-examples/files/5588552/test.zip)

**Comment by vojtech-chalupa** [comment]
Hello, just letting you know that I've finally managed to replicate both your issues. I will pass this info on to @mpospisil. 
The issues come up when I click the "Connections" button first and the "Member" button second in the CCM app.

In the meantime, could you please try the following workflow?
1) clear the test directory in Documents\FEAppExample_1
2) load your model and launch CCM
3) **click the Member button first**
4) configure the connections
5) configure the Member
6) open the Member 

This doesn't produce any issues on my side. Let me know if this works for you as well.
Thank you, we will get back to you with the solution shortly.

**Comment by johnnyontheweb** [comment]
Thanks for the reply. I can confirm that the suggested procedure does not prodice any issue.
I always clicked on Connections first, during a skype call with you I was told that a single Member would need all ands to be a configured connection. The process you suggested leads to the same results, but I hope this will be corrected
I'll wait for your updates - in the meanwhile I kindly ask to clarify what the button "Synchronize all" is inteded for.

thanks in advance, regards

**Comment by vojtech-chalupa** [comment]
Hello, the bug has now been solved. The fix will be a part of the next patch coming this week.

**Comment by johnnyontheweb** [comment]
thanks you
