### ISSUE TITLE
"An error occured during import" with sample files

### ISSUE THREAD

**Issue by ozbuild** [idea-statica/ccm-examples#15]
We get an error "An error occurred during import. Object reference not set to an instance of an object" when we try and use the ccm-examples-release-v20.1 project to open one of your sample files tube-connection.

The attached zip file contains the step by step procedure we used to produce the error. Plus an extract of the error log. It looks like maybe something to do with a steelAus update item ?
[IdeaStatiCaCodeCheckManager.zip](https://github.com/idea-statica/ccm-examples/files/5985881/IdeaStatiCaCodeCheckManager.zip)

**Comment by vojtech-chalupa** [comment]
Hello, I've replicated the issue and I am sending it to deve to investigate.

**Comment by ozbuild** [comment]
Thank you

Regards

Mark Watson
SPACE GASS Support

**Comment by vadura-pavel** [comment]
Hello,
I investigate your example and found issue. You need to specify tag connections. In attachment you can see how to fill in your case.
You can also check our example how to fill IOM model see [https://idea-statica.github.io/iom-examples/iom-steel-connections/steel-frame1.html](https://idea-statica.github.io/iom-examples/iom-steel-connections/steel-frame1.html)

[missing tag.txt](https://github.com/idea-statica/ccm-examples/files/6067889/missing.tag.txt)

**Comment by ozbuild** [comment]
Thanks for your valuable information but that did not answer my question.

I will rephrase my question and use your sample files.

Using your connectionFromIOM-web.ideaCon sample file

My question is “What is the definition of the label End and Begin in the Member column of the Load table ?”

[cid:image001.jpg@01D710ED.D8336760]

If you look at the sample result file IOM-SteelFrame.xmlR, the values displayed in the load data are from Position 0 which I thought would be “begin” and I therefore thought the label would be the “M1/Begin” ?

[cid:image003.jpg@01D710ED.D8336760]

[cid:image007.png@01D710E9.EEE0E720]





Regards

Mark Watson
