### ISSUE TITLE
open ccm still crashes

### ISSUE THREAD

**Issue by GerryArk** [idea-statica/ccm-examples#4]
I have followed the  FAQ , added the message , set project name 
but still facing crashes as soon I recall the connection

Second issue, after recalling the plugin for the first time, no window opens on the second attempt 
if we do not remove the folder created at the first step 

I have also download the new example FEA1Example  and the tube-connection  crashes in the same way 

gd

**Comment by mpospisil** [comment]
I've just imported your modified ModelBIM - https://github.com/idea-statica/ccm-examples/blob/master/FEAppExample_1/Examples/tube-conenction.xml using the latest Idea Statica v20 - this is the result :

Make sure your project folder is deleted and try it again - it must work.

![tube-connection](https://user-images.githubusercontent.com/19650653/91733119-74cfd780-eba9-11ea-8073-bc42c24963a6.PNG)

**Comment by GerryArk** [comment]
Yes making a clear of the dirs it worked 
Now I would like to know how connections can be added 
if we return  to the same project  and different nodes need to be detailed 
which is the rule ?

**Comment by GerryArk** [comment]
Hi Martin

Just to let You know that now all works fine
I have configured the app so user can make connections
using any code

tested all codes and it seems all Ok

thanks


Gerry D'Anza Architect

CEO ixRay ltda
Dr.Emilio Frugoni
1109 Montevideo
11200 Uruguay





------ Original Message ------
