### ISSUE TITLE
Uncorrect exportation of nodes

### ISSUE THREAD

**Issue by thema1996** [idea-statica/ccm-examples#5]
Hello, 
I write this post to solve a problem that we discover in the exportation of nodes that has more than 5 members that converge in the same intersection. In particular we use PRO_SAP calculation program, that use PRO_Idea plug-in for the exportation of nodes from PRO_SAP to Idea_Connection. The problem is that the importation windows of the plug-in cut the button "OK", in the bottom part of the window, necessary to joint the horizontal or the vertical elements that are continuous in the node. We had almost solve that problem using the IOM application to open the .xml file create by the plug-in, in this case we can joint the two element, but when we export the file in Idea_Conection there is a problem with the exportation because the load combination are not fully exported or they are not exported at all.
Could you kindly do something to solve our problem?
I put a link below in wich you can download a video with the full explenation of our problem

https://we.tl/t-pUBoRVyKd3

Thanks for your support.

Ing. Francesco Fenocchio

**Comment by mpospisil** [comment]
I have looked at your video. I can see you are using the old API which is obsolete and we don't support it. I would suggest to try to import it using our new API as it is described in this example

https://github.com/idea-statica/ccm-examples

if it doesn't work please attach your ModelBIM (xml file) we will help you to fix it. We have done a lot of improvements related to import (geometry and loading) and I believe it will work. It is the easiest way how to fix it ( for us and for you)

**Comment by thema1996** [comment]
Hello,
Thanks for the quick answer, I’d tried to use Code Check Manger but I think that PRO_SAP doesn’t support it. There is no link in the program that allow me to access to the code check manager and I ‘m not able to open from IDEA STATICA.
Thanks for your support.
Best Regards

Da: Martin Pospisil <notifications@github.com>
Inviato: lunedì 31 agosto 2020 17:08
A: idea-statica/ccm-examples <ccm-examples@noreply.github.com>
Cc: b6 <b6@thema96.it>; Author <author@noreply.github.com>
Oggetto: Re: [idea-statica/ccm-examples] Uncorrect exportation of nodes (#5)


I have looked at your video. I can see you are using the old API which is obsolete and we don't support it. I would suggest to try to import it using our new API as it is described in this example

https://github.com/idea-statica/ccm-examples

if it doesn't work please attach your ModelBIM (xml file) we will help you to fix it. We have done a lot of improvements related to import (geometry and loading) and I believe it will work. It is the easiest way how to fix it ( for us and for you)

**Comment by thema1996** [comment]
Hello,
Thanks for the quick answer, I’d tried to use Code Check Manger but I think that PRO_SAP doesn’t support it. There is no link in the program that allow me to access to the code check manager and I ‘m not able to open from IDEA STATICA. 
Thanks for your support.
Best Regards
