### ISSUE TITLE
Problem about opening a fem model with code check manager

### ISSUE THREAD

**Issue by thema1996** [idea-statica/ccm-examples#6]
Hello we use PRO_SAP calculation software and we had some problem to export nodes that has more than 5 mebers with the plug-in PRO_Idea, so you had suggest us to use the Code Check Manager to make the exportation, our problme is that we are not able to open our model in the code check manager, can you told us how to do this operation because we can't do it following the guide that you gave to us.
Thanks for the support.
Best Regards.
Ing. Francesco Fenocchio

**Comment by mpospisil** [comment]
Are you able to build and run this example (I mean without PRO_SAP) ? It would be the first step.

Next step would be to implement a plugin which can create an instance of ModelBIM from your model.

**Comment by thema1996** [comment]
Unfortunately we are not able to run the example, I try to open the example file with code check manger but we I go to open model page it can’t read the project so I can’t open any model.

Da: Martin Pospisil <notifications@github.com>
Inviato: lunedì 7 settembre 2020 13:53
A: idea-statica/ccm-examples <ccm-examples@noreply.github.com>
Cc: b6 <b6@thema96.it>; Author <author@noreply.github.com>
Oggetto: Re: [idea-statica/ccm-examples] Problem about opening a fem model with code check manager (#6)


Are you able to build and run this example (I mean without PRO_SAP) ? It would be the first step.

Next step would be to implement a plugin which can create an instance of ModelBIM from your model.

**Comment by thema1996** [comment]
Unfortunately we are not able to run the example, I try to open the example file with code check manger but we I go to open model page it can’t read the project so I can’t open any model.

**Comment by mpospisil** [comment]
Which version of IS is intalled on your PC ?

Did you open ccm-examples.sln in Visual Studio ?

Did ou modify Settings for the project FEAppExample_1.csproj so that the correct path to idea statica is set ?

Can you start debuuging of the project  FEAppExample_1.csproj from Visual Studio ?

Can you open default_project.xml in running FEAppExample_1.exe ?

Can you run CCM by clicking on the button **Run IDEA StatiCa CCM** ?

Then CCMshould start and an user should select the design code for CCM project. Then you can click on the button **Connection** in the Tab Import

From your description it is not clear what you try to do and in which step the problem occurs

**Comment by thema1996** [comment]
Hello,

  1.  For IS did you mean operating system? If yes, we have windows 10 on the pc in which we had installed Idea_Statica.
  2.  Yes I have modify the path to the folder of Idea Statica in which there is the ideacodecheck.exe file
  3.  Yes I open it in visual studio but the debugging fails cause in the example files there is no FEAppExample_1.exe
  4.  No because the file FEAppExample_1.exe is missing
  5.  No because the steps before fails.
Thanks for your support.
Best Regards.
Ing. Francesco Fenocchio

Da: Martin Pospisil <notifications@github.com>
Inviato: martedì 8 settembre 2020 15:05
A: idea-statica/ccm-examples <ccm-examples@noreply.github.com>
Cc: b6 <b6@thema96.it>; Author <author@noreply.github.com>
Oggetto: Re: [idea-statica/ccm-examples] Problem about opening a fem model with code check manager (#6)


Which version of IS is intalled on your PC ?

Did you open ccm-examples.sln in Visual Studio ?

Did ou modify Settings for the project FEAppExample_1.csproj so that the correct path to idea statica is set ?

Can you start debuuging of the project FEAppExample_1.csproj from Visual Studio ?

Can you open default_project.xml in running FEAppExample_1.exe ?

Can you run CCM by clicking on the button Run IDEA StatiCa CCM ?

Then CCMshould start and an user should select the design code for CCM project. Then you can click on the button Connection in the Tab Import

From your description it is not clear what you try to do and in which step the problem occurs

**Comment by mpospisil** [comment]
Francesco,  we can organize a web meeting and look at it together. Send me an email to plan it (if you want)

**Comment by thema1996** [comment]
Good Morining Martin,

It would be great if we can do a web meeting to solve the problem. We can do it also tomorrow or when you are free from others commitments. For the time we can do it in the morning like 11:00 time zone of Rome.

Let me know about the meeting time. Thanks for the support.

Best Regards

Ing. Francesco Fenocchio


Da: Martin Pospisil <notifications@github.com>
Inviato: mercoledì 16 settembre 2020 09:13
A: idea-statica/ccm-examples <ccm-examples@noreply.github.com>
Cc: b6 <b6@thema96.it>; Author <author@noreply.github.com>
Oggetto: Re: [idea-statica/ccm-examples] Problem about opening a fem model with code check manager (#6)


Francesco, we can organize a web meeting and look at it together. Send me an email to plan it (if you want)

**Comment by mpospisil** [comment]
Hi  Francesco,

can we do it at 10am tomorrow?

Martin

**Comment by mpospisil** [comment]
I will be available at 11:00 - send me an email martin.pospisil@ideastatica.com
